## NOIDA

In [2]:
import pandas as pd

In [70]:
jan=pd.read_csv('Downloads/project/noida/JAN_MARCH_Prices_Noida.csv')

In [71]:
aug=pd.read_csv('Downloads/project/noida/Aug_DEC_NOIDA.csv')

In [72]:
feb=pd.read_csv('Downloads/project/noida/Feb_july_Prices_Noida.csv')

In [75]:
jan.head()

,Dates,"('Onion Big',)","('Onion Small',)","('Tomato',)","('Green Chilli',)","('Beetroot',)","('Potato',)","('Raw Banana (Plantain)',)","('Amaranth Leaves',)","('Amla',)",...,"('Mustard Leaves',)","('Ladies Finger',)","('Pumpkin',)","('Radish',)","('Ridge Gourd',)","('Shallot (Pearl Onion)',)","('Snake Gourd',)","('Sorrel Leaves',)","('Spinach',)","('Sweet Potato',)"
0,2023-01-01,30,39,16,32,37,32,9,12,70,...,18,29,30,26,28,36,28,12,13,38
1,2023-01-02,27,38,18,34,36,25,7,10,60,...,15,31,28,26,28,29,31,15,10,37
2,2023-01-03,27,38,18,34,36,25,7,10,60,...,15,31,28,26,28,29,31,15,10,37
3,2023-01-04,25,39,20,37,34,27,7,11,70,...,16,30,26,25,29,36,27,12,13,40
4,2023-01-05,25,39,20,37,34,27,7,11,70,...,16,30,26,25,29,36,27,12,13,40

In [76]:
dataframes = [feb, aug, jan]
df = pd.concat(dataframes)

In [77]:
df

,Dates,"('Onion Big',)","('Onion Small',)","('Tomato',)","('Green Chilli',)","('Beetroot',)","('Potato',)","('Raw Banana (Plantain)',)","('Mint Leaves',)","('Amla',)",...,"('Radish',)","('Ridge Gourd',)","('Shallot (Pearl Onion)',)","('Snake Gourd',)","('Sorrel Leaves',)","('Spinach',)","('Sweet Potato',)","('Onion Big',).1","('Onion Big',).2","('Amaranth Leaves',)"
0,2022-02-01,40,61.0,19.0,38,46,23,6,9,50,...,24,30,37,24,12,12,40,NaN,NaN,NaN
1,2022-02-02,33,65.0,18.0,39,50,26,5,6,50,...,23,29,34,25,12,10,40,NaN,NaN,NaN
2,2022-02-03,33,65.0,18.0,39,50,26,5,6,50,...,23,29,34,25,12,10,40,NaN,NaN,NaN
3,2022-02-04,33,65.0,18.0,39,50,26,5,6,50,...,23,29,34,25,12,10,40,NaN,NaN,NaN
4,2022-02-05,38,62.0,20.0,37,46,26,6,10,50,...,20,30,31,27,13,12,40,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2023-03-27,22,56.0,23.0,45,30,31,9,5,70,...,26,31,32,28,12,12,39,NaN,NaN,13.0
86,2023-03-28,22,56.0,23.0,45,30,31,9,5,70,...,26,31,32,28,12,12,39,NaN,NaN,13.0
87,2023-03-29,18,55.0,21.0,41,28,32,10,6,50,...,25,30,34,30,14,15,39,NaN,NaN,14.0
88,2023-03-30,18,55.0,21.0,41,28,32,10,6,50,...,25,30,34,30,14,15,39,NaN,NaN,14.0
89,2023-03-31,18,55.0,21.0,41,28,32,10,6,50,...,25,30,34,30,14,15,39,NaN,NaN,14.0

In [176]:
df.columns = df.columns.str.replace(r'[()\,]', '', regex=True).str.strip()

In [99]:
path = 'C:\\Users\\91982\\Downloads\\project\\NOIDA_FEB22_MARCH23.csv'
df.to_csv(path, index=False)

# DELHI

In [177]:
jan=pd.read_csv('Downloads/project/noida/JAN_MARCH_Prices_DELHI.csv')
aug=pd.read_csv('Downloads/project/noida/Aug_DEC_DELHI.csv')
feb=pd.read_csv('Downloads/project/noida/Feb_july_Prices_DELHI.csv')

In [178]:
dataframes = [feb, aug, jan]
df = pd.concat(dataframes)

In [179]:
df

,Dates,"('Onion Big',)","('Onion Small',)","('Tomato',)","('Green Chilli',)","('Beetroot',)","('Potato',)","('Raw Banana (Plantain)',)","('Mint Leaves',)","('Amla',)","('Ash gourd',)","('Baby Corn',)","('Banana Flower',)","('Capsicum',)","('Bitter Gourd',)","('Bottle Gourd',)","('Butter Beans',)","('Broad Beans',)","('Cabbage',)","('Carrot',)","('Cauliflower',)","('Cluster beans',)","('Coconut',)","('Colocasia Leaves',)","('Colocasia',)","('Coriander Leaves',)","('Corn',)","('Cucumber',)","('Curry Leaves',)","('Dill Leaves',)","('Drumsticks',)","('Brinjal',)","('Brinjal (Big)',)","('Elephant Yam',)","('Fenugreek Leaves',)","('French Beans',)","('Garlic',)","('Ginger',)","('Onion Green',)","('Green Peas',)","('Ivy Gourd',)","('Lemon (Lime)',)","('Mango Raw',)","('Mint Leaves',).1","('Mushroom',)","('Mustard Leaves',)","('Ladies Finger',)","('Pumpkin',)","('Radish',)","('Ridge Gourd',)","('Shallot (Pearl Onion)',)","('Snake Gourd',)","('Sorrel Leaves',)","('Spinach',)","('Sweet Potato',)",Onion small,Tomato,"('Amaranth Leaves',)"
0,2022-02-01,40,61.0,19.0,38,46,23,6,9,50,20,52,16,44,34,25,41,43,26,69,44,49,33,14,24,8,33,14,36,18,150,32,64,25,13,41,63,32,36,48,34,36,81,9.0,83,19,56,23,24,30,37,24,12,12,40,NaN,NaN,NaN
1,2022-02-02,33,65.0,18.0,39,50,26,5,6,50,28,58,16,48,33,28,43,47,27,70,42,46,35,13,27,7,35,15,41,12,130,29,60,24,11,41,64,31,44,51,37,39,81,6.0,88,16,59,21,23,29,34,25,12,10,40,NaN,NaN,NaN
2,2022-02-03,33,65.0,18.0,39,50,26,5,6,50,28,58,16,48,33,28,43,47,27,70,42,46,35,13,27,7,35,15,41,12,130,29,60,24,11,41,64,31,44,51,37,39,81,6.0,88,16,59,21,23,29,34,25,12,10,40,NaN,NaN,NaN
3,2022-02-04,33,65.0,18.0,39,50,26,5,6,50,28,58,16,48,33,28,43,47,27,70,42,46,35,13,27,7,35,15,41,12,130,29,60,24,11,41,64,31,44,51,37,39,81,6.0,88,16,59,21,23,29,34,25,12,10,40,NaN,NaN,NaN
4,2022-02-05,38,62.0,20.0,37,46,26,6,10,50,25,53,15,44,33,27,43,41,29,67,44,47,33,14,25,11,32,16,42,14,120,26,62,24,14,42,66,29,36,56,32,39,78,10.0,75,16,54,26,20,30,31,27,13,12,40,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2023-03-27,22,56.0,23.0,45,30,31,9,5,70,21,59,14,45,33,27,47,38,11,29,25,44,28,13,27,6,27,29,25,14,100,27,29,29,11,42,52,50,45,83,27,55,86,NaN,84,14,47,20,26,31,32,28,12,12,39,NaN,NaN,13.0
86,2023-03-28,22,56.0,23.0,45,30,31,9,5,70,21,59,14,45,33,27,47,38,11,29,25,44,28,13,27,6,27,29,25,14,100,27,29,29,11,42,52,50,45,83,27,55,86,NaN,84,14,47,20,26,31,32,28,12,12,39,NaN,NaN,13.0
87,2023-03-29,18,55.0,21.0,41,28,32,10,6,50,20,59,21,48,33,26,50,41,14,29,24,41,26,16,28,6,28,30,28,10,120,20,23,29,9,42,58,44,44,81,22,54,98,NaN,72,16,50,24,25,30,34,30,14,15,39,NaN,NaN,14.0
88,2023-03-30,18,55.0,21.0,41,28,32,10,6,50,20,59,21,48,33,26,50,41,14,29,24,41,26,16,28,6,28,30,28,10,120,20,23,29,9,42,58,44,44,81,22,54,98,NaN,72,16,50,24,25,30,34,30,14,15,39,NaN,NaN,14.0
89,2023-03-31,18,55.0,21.0,41,28,32,10,6,50,20,59,21,48,33,26,50,41,14,29,24,41,26,16,28,6,28,30,28,10,120,20,23,29,9,42,58,44,44,81,22,54,98,NaN,72,16,50,24,25,30,34,30,14,15,39,NaN,NaN,14.0

In [180]:
df.columns = df.columns.str.replace(r'[()\,]', '', regex=True).str.strip()

In [181]:
path = 'C:\\Users\\91982\\Downloads\\project\\NOIDA_FEB22_MARCH23.csv'
df.to_csv(path, index=False)

## DATA CLEANING

In [153]:
delhi=pd.read_csv('Downloads/project/DELHI_FEB22_MARCH23.csv')

In [154]:
delhi.isna().sum()

Dates                    1
Fenugreek Leaves         3
Onion Big                1
Onion Small              1
Tomato                   1
Green Chilli             1
Beetroot                 1
Potato                   1
Raw Banana Plantain      1
Amaranth Leaves          1
Amla                     1
Ash gourd                1
Baby Corn                1
Banana Flower            1
Capsicum                 1
Bitter Gourd             1
Bottle Gourd             1
Butter Beans             1
Broad Beans              1
Cabbage                  1
Carrot                   1
Cauliflower              1
Cluster beans            1
Coconut                  1
Colocasia Leaves         1
Colocasia                1
Coriander Leaves         1
Corn                     1
Cucumber                 1
Curry Leaves             1
Dill Leaves              1
Drumsticks               1
Brinjal                  1
Brinjal Big              1
Elephant Yam             1
French Beans             1
Garlic                   1
Ginger                   1
Onion Green              1
Green Peas               1
Ivy Gourd                1
Lemon Lime               1
Mango Raw                1
Mint Leaves              1
Mushroom                 1
Mustard Leaves           1
Ladies Finger            1
Pumpkin                  1
Radish                   1
Ridge Gourd              1
Shallot Pearl Onion      1
Snake Gourd              1
Sorrel Leaves            1
Spinach                  1
Sweet Potato             1
Column1                423
dtype: int64

In [155]:
delhi.drop('Column1',axis=1,inplace=True)

In [156]:
delhi.dropna(inplace=True)

In [141]:
delhi.isna().sum()

Dates                  0
Fenugreek Leaves       0
Onion Big              0
Onion Small            0
Tomato                 0
Green Chilli           0
Beetroot               0
Potato                 0
Raw Banana Plantain    0
Amaranth Leaves        0
Amla                   0
Ash gourd              0
Baby Corn              0
Banana Flower          0
Capsicum               0
Bitter Gourd           0
Bottle Gourd           0
Butter Beans           0
Broad Beans            0
Cabbage                0
Carrot                 0
Cauliflower            0
Cluster beans          0
Coconut                0
Colocasia Leaves       0
Colocasia              0
Coriander Leaves       0
Corn                   0
Cucumber               0
Curry Leaves           0
Dill Leaves            0
Drumsticks             0
Brinjal                0
Brinjal Big            0
Elephant Yam           0
French Beans           0
Garlic                 0
Ginger                 0
Onion Green            0
Green Peas             0
Ivy Gourd              0
Lemon Lime             0
Mango Raw              0
Mint Leaves            0
Mushroom               0
Mustard Leaves         0
Ladies Finger          0
Pumpkin                0
Radish                 0
Ridge Gourd            0
Shallot Pearl Onion    0
Snake Gourd            0
Sorrel Leaves          0
Spinach                0
Sweet Potato           0
dtype: int64

In [147]:
noida=pd.read_csv('Downloads/project/NOIDA_FEB22_MARCH23.csv')

In [148]:
noida

,Dates,Onion Big,Onion Small,Tomato,Green Chilli,Beetroot,Potato,Raw Banana Plantain,Mint Leaves,Amla,Ash gourd,Baby Corn,Banana Flower,Capsicum,Bitter Gourd,Bottle Gourd,Butter Beans,Broad Beans,Cabbage,Carrot,Cauliflower,Cluster beans,Coconut,Colocasia Leaves,Colocasia,Coriander Leaves,Corn,Cucumber,Curry Leaves,Dill Leaves,Drumsticks,Brinjal,Brinjal Big,Elephant Yam,Fenugreek Leaves,French Beans,Garlic,Ginger,Onion Green,Green Peas,Ivy Gourd,Lemon Lime,Mango Raw,Mint Leaves.1,Mushroom,Mustard Leaves,Ladies Finger,Pumpkin,Radish,Ridge Gourd,Shallot Pearl Onion,Snake Gourd,Sorrel Leaves,Spinach,Sweet Potato,Amaranth Leaves
0,01-02-2022,40,61,19,38,46,23,6,9,50,20,52,16,44,34,25,41,43,26,69,44,49,33,14,24,8,33,14,36,18,150,32,64,25,13,41,63,32,36,48,34,36,81,9.0,83,19,56,23,24,30,37,24,12,12,40,18
1,02-02-2022,33,65,18,39,50,26,5,6,50,28,58,16,48,33,28,43,47,27,70,42,46,35,13,27,7,35,15,41,12,130,29,60,24,11,41,64,31,44,51,37,39,81,6.0,88,16,59,21,23,29,34,25,12,10,40,16
2,03-02-2022,33,65,18,39,50,26,5,6,50,28,58,16,48,33,28,43,47,27,70,42,46,35,13,27,7,35,15,41,12,130,29,60,24,11,41,64,31,44,51,37,39,81,6.0,88,16,59,21,23,29,34,25,12,10,40,16
3,04-02-2022,33,65,18,39,50,26,5,6,50,28,58,16,48,33,28,43,47,27,70,42,46,35,13,27,7,35,15,41,12,130,29,60,24,11,41,64,31,44,51,37,39,81,6.0,88,16,59,21,23,29,34,25,12,10,40,16
4,05-02-2022,38,62,20,37,46,26,6,10,50,25,53,15,44,33,27,43,41,29,67,44,47,33,14,25,11,32,16,42,14,120,26,62,24,14,42,66,29,36,56,32,39,78,10.0,75,16,54,26,20,30,31,27,13,12,40,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,27-03-2023,22,56,23,45,30,31,9,5,70,21,59,14,45,33,27,47,38,11,29,25,44,28,13,27,6,27,29,25,14,100,27,29,29,11,42,52,50,45,83,27,55,86,NaN,84,14,47,20,26,31,32,28,12,12,39,13
420,28-03-2023,22,56,23,45,30,31,9,5,70,21,59,14,45,33,27,47,38,11,29,25,44,28,13,27,6,27,29,25,14,100,27,29,29,11,42,52,50,45,83,27,55,86,NaN,84,14,47,20,26,31,32,28,12,12,39,13
421,29-03-2023,18,55,21,41,28,32,10,6,50,20,59,21,48,33,26,50,41,14,29,24,41,26,16,28,6,28,30,28,10,120,20,23,29,9,42,58,44,44,81,22,54,98,NaN,72,16,50,24,25,30,34,30,14,15,39,14
422,30-03-2023,18,55,21,41,28,32,10,6,50,20,59,21,48,33,26,50,41,14,29,24,41,26,16,28,6,28,30,28,10,120,20,23,29,9,42,58,44,44,81,22,54,98,NaN,72,16,50,24,25,30,34,30,14,15,39,14
423,31-03-2023,18,55,21,41,28,32,10,6,50,20,59,21,48,33,26,50,41,14,29,24,41,26,16,28,6,28,30,28,10,120,20,23,29,9,42,58,44,44,81,22,54,98,NaN,72,16,50,24,25,30,34,30,14,15,39,14

In [152]:
noida.isna().sum()

Dates                  0
Onion Big              0
Onion Small            0
Tomato                 0
Green Chilli           0
Beetroot               0
Potato                 0
Raw Banana Plantain    0
Mint Leaves            0
Amla                   0
Ash gourd              0
Baby Corn              0
Banana Flower          0
Capsicum               0
Bitter Gourd           0
Bottle Gourd           0
Butter Beans           0
Broad Beans            0
Cabbage                0
Carrot                 0
Cauliflower            0
Cluster beans          0
Coconut                0
Colocasia Leaves       0
Colocasia              0
Coriander Leaves       0
Corn                   0
Cucumber               0
Curry Leaves           0
Dill Leaves            0
Drumsticks             0
Brinjal                0
Brinjal Big            0
Elephant Yam           0
Fenugreek Leaves       0
French Beans           0
Garlic                 0
Ginger                 0
Onion Green            0
Green Peas             0
Ivy Gourd              0
Lemon Lime             0
Mango Raw              0
Mushroom               0
Mustard Leaves         0
Ladies Finger          0
Pumpkin                0
Radish                 0
Ridge Gourd            0
Shallot Pearl Onion    0
Snake Gourd            0
Sorrel Leaves          0
Spinach                0
Sweet Potato           0
Amaranth Leaves        0
dtype: int64

In [182]:
noida.columns

Index(['Dates', 'Onion Big', 'Onion Small', 'Tomato', 'Green Chilli',
       'Beetroot', 'Potato', 'Raw Banana Plantain', 'Mint Leaves', 'Amla',
       'Ash gourd', 'Baby Corn', 'Banana Flower', 'Capsicum', 'Bitter Gourd',
       'Bottle Gourd', 'Butter Beans', 'Broad Beans', 'Cabbage', 'Carrot',
       'Cauliflower', 'Cluster beans', 'Coconut', 'Colocasia Leaves',
       'Colocasia', 'Coriander Leaves', 'Corn', 'Cucumber', 'Curry Leaves',
       'Dill Leaves', 'Drumsticks', 'Brinjal', 'Brinjal Big', 'Elephant Yam',
       'Fenugreek Leaves', 'French Beans', 'Garlic', 'Ginger', 'Onion Green',
       'Green Peas', 'Ivy Gourd', 'Lemon Lime', 'Mango Raw', 'Mushroom',
       'Mustard Leaves', 'Ladies Finger', 'Pumpkin', 'Radish', 'Ridge Gourd',
       'Shallot Pearl Onion', 'Snake Gourd', 'Sorrel Leaves', 'Spinach',
       'Sweet Potato', 'Amaranth Leaves'],
      dtype='object')

# converting names of vegetables into rows

In [7]:
df=pd.read_csv('Downloads/Delhi_new.csv')

In [8]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [9]:
new_df = pd.melt(df, id_vars=['Dates'], var_name='Vegetable', value_name='Price')
# Rename the 'Dates' column to 'Date'
new_df.rename(columns={'Dates': 'Date'}, inplace=True)

In [10]:
new_df

             Date          Vegetable  Price
0      01-02-2022  Fenugreek Leaves    11.0
1      02-02-2022  Fenugreek Leaves    13.0
2      03-02-2022  Fenugreek Leaves    13.0
3      04-02-2022  Fenugreek Leaves    13.0
4      05-02-2022  Fenugreek Leaves     8.0
...           ...                ...    ...
22729  27-03-2023       Sweet Potato   36.0
22730  28-03-2023       Sweet Potato   36.0
22731  29-03-2023       Sweet Potato   37.0
22732  30-03-2023       Sweet Potato   37.0
22733  31-03-2023       Sweet Potato   37.0

[22734 rows x 3 columns]